CREATE DATABASE IF NOT EXISTS todo;
USE todo;

CREATE TABLE task (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    userId VARCHAR(255) NOT NULL ,
    isCompleted BOOLEAN NOT NULL,
    deadline DATETIME NOT NULL,
    completed_at DATETIME NULL
);
